# Generated by Django 6.0 on 2025-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Canteen Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('daily_lunch_count', models.IntegerField(default=0, verbose_name='Daily Lunch Count')),
                ('daily_dinner_count', models.IntegerField(default=0, verbose_name='Daily Dinner Count')),
            ],
            options={
                'verbose_name': 'Canteen',
                'verbose_name_plural': 'Canteens',
            },
        ),
    ]
