# Generated by Django 6.0 on 2025-12-09 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Staff Name')),
                ('role', models.CharField(choices=[('Cook', 'Cook'), ('Helper', 'Helper')], default='Helper', max_length=10, verbose_name='Role')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Salary')),
                ('canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.canteen', verbose_name='Assigned Canteen')),
            ],
            options={
                'verbose_name': 'Staff Member',
                'verbose_name_plural': 'Staff',
            },
        ),
    ]
