# Generated by Django 6.0 on 2025-12-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(verbose_name='Leave Date')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason for Leave')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Staff Leave',
                'verbose_name_plural': 'Staff Leaves',
                'unique_together': {('staff', 'leave_date')},
            },
        ),
    ]
