# Generated by Django 6.0 on 2025-12-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_staffleave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffleave',
            options={'verbose_name': 'Staff Leave (Period)', 'verbose_name_plural': 'Staff Leaves (Periods)'},
        ),
        migrations.AlterUniqueTogether(
            name='staffleave',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffleave',
            name='end_date',
            field=models.DateField(default='2025-01-01', verbose_name='End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffleave',
            name='start_date',
            field=models.DateField(default='2025-01-01', verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='staffleave',
            name='leave_date',
        ),
    ]
