# Generated by Django 6.0 on 2025-12-09 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_staffleave_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('category', models.CharField(choices=[('Kirana', 'Kirana/Grocery'), ('Gas', 'Gas Cylinder/Fuel'), ('Salary', 'Salary/Wages'), ('Other', 'Other Expenses')], max_length=50, verbose_name='Category')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Quantity')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Paid Status')),
                ('canteen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.canteen', verbose_name='Associated Canteen')),
            ],
            options={
                'verbose_name': 'Expense Entry',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
