# Generated by Django 6.0 on 2025-12-09 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Payment Date')),
                ('payment_type', models.CharField(choices=[('Monthly', 'Monthly Salary Payment'), ('Advance', 'Advance Payment'), ('Bonus', 'Bonus')], max_length=10, verbose_name='Payment Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Details')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff', verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Salary/Advance Payment',
                'verbose_name_plural': 'Salary Payments',
                'ordering': ['-date'],
            },
        ),
    ]
