# Generated by Django 6.0 on 2025-12-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_salarypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='billing_type',
            field=models.CharField(choices=[('DAILY', 'Daily Payment/Tracking'), ('MONTHLY', 'Monthly Fixed Billing')], default='DAILY', max_length=10, verbose_name='Billing Type'),
        ),
    ]
