# Generated by Django 6.0 on 2025-12-10 06:23

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_canteen_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Entry Date')),
                ('lunch_qty', models.IntegerField(default=0, verbose_name='Lunch Qty')),
                ('dinner_qty', models.IntegerField(default=0, verbose_name='Dinner Qty')),
                ('nasta_qty', models.IntegerField(default=0, verbose_name='Nasta Qty')),
                ('tea_qty', models.IntegerField(default=0, verbose_name='Tea Qty')),
                ('cash_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cash Payment Received')),
                ('online_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Online Payment Received')),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.canteen', verbose_name='Canteen Name')),
            ],
            options={
                'verbose_name': 'Daily Service/Payment Entry',
                'verbose_name_plural': 'Daily Entries',
                'ordering': ['-date', 'canteen__name'],
                'unique_together': {('canteen', 'date')},
            },
        ),
    ]
