# Generated by Django 6.0 on 2025-12-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_dailyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyentry',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Cash Payment Received'),
        ),
        migrations.AlterField(
            model_name='dailyentry',
            name='online_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Online Payment Received'),
        ),
    ]
