# Generated by Django 6.0 on 2025-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_dailyentry_cash_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='guest_token_qty',
            field=models.IntegerField(default=0, verbose_name='Guest Token Qty'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='normal_token_qty',
            field=models.IntegerField(default=0, verbose_name='Normal Token Qty'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='special_token_qty',
            field=models.IntegerField(default=0, verbose_name='Special Token Qty'),
        ),
    ]
