# Generated by Django 6.0 on 2025-12-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_dailyentry_guest_token_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Kirana', 'Kirana/Grocery'), ('Gas', 'Gas Cylinder/Fuel'), ('Salary', 'Salary/Wages'), ('Milk', 'Milk/Dairy'), ('Auto', 'Auto Rickshaw/Transport'), ('Wood', 'Wood/Fuel'), ('Other', 'Other Expenses')], max_length=50, verbose_name='Category'),
        ),
    ]
