# Generated by Django 6.0 on 2025-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Pending', '🔴 Pending / Baki'), ('Cash', '🟢 Paid - Cash'), ('Online', '🔵 Paid - Online')], default='Cash', max_length=20, verbose_name='Payment Status'),
        ),
    ]
