# Generated by Django 6.0 on 2025-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_expense_is_paid_expense_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Pending', '🔴 Pending / Due'), ('Cash', '🟢 Paid - Cash'), ('Online', '🔵 Paid - Online')], default='Cash', max_length=20, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
    ]
