# Generated by Django 6.0 on 2025-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_expense_payment_mode_alter_staff_joining_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, verbose_name='Phone Number'),
        ),
    ]
