# Generated by Django 6.0 on 2025-12-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_staff_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='aadhar_card',
            field=models.ImageField(blank=True, null=True, upload_to='staff_aadhar/', verbose_name='Aadhar Card Photo'),
        ),
        migrations.AddField(
            model_name='staff',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Staff Photo'),
        ),
    ]
