# Generated by Django 6.0 on 2025-12-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
