# Generated by Django 6.0 on 2025-12-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_delete_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Account No'),
        ),
        migrations.AddField(
            model_name='staff',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Kirana', 'Kirana/Grocery'), ('Gas', 'Gas Cylinder/Fuel'), ('Vegetables', 'Vegetables (Sabzi)'), ('Milk', 'Milk/Dairy'), ('Auto', 'Auto Rickshaw/Transport'), ('Wood', 'Wood/Fuel'), ('Other', 'Other Expenses')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
