# Generated by Django 6.0 on 2025-12-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_staff_bank_account_no_staff_ifsc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='nasta_qty',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='evening_breakfast',
            field=models.CharField(blank=True, help_text='Evening breakfast', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='morning_breakfast',
            field=models.CharField(blank=True, help_text='Morning breakfast', max_length=200, null=True),
        ),
    ]
