# Generated by Django 6.0 on 2025-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_remove_dailyentry_nasta_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyentry',
            name='evening_breakfast',
        ),
        migrations.RemoveField(
            model_name='dailyentry',
            name='morning_breakfast',
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='nasta_qty',
            field=models.IntegerField(default=0, verbose_name='Nasta Qty'),
        ),
    ]
