# Generated by Django 6.0 on 2025-12-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_remove_dailyentry_evening_breakfast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffleave',
            name='is_paid_leave',
            field=models.BooleanField(default=False, verbose_name="Paid Leave (Don't Cut Salary)"),
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_days', models.IntegerField(default=30)),
                ('working_days', models.IntegerField(default=0)),
                ('paid_leaves', models.IntegerField(default=0)),
                ('unpaid_leaves', models.IntegerField(default=0)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generated_on', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.staff')),
            ],
        ),
    ]
