# Generated by Django 6.0 on 2025-12-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_staffleave_is_paid_leave_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Kirana', 'Kirana/Grocery'), ('Gas', 'Gas Cylinder/Fuel'), ('Vegetables', 'Vegetables (Sabzi)'), ('Milk', 'Milk/Dairy'), ('Auto', 'Auto Rickshaw/Transport'), ('Wood', 'Wood/Fuel'), ('Disposable', 'Disposable'), ('Other', 'Other Expenses')], max_length=100, verbose_name='Category'),
        ),
    ]
