# Generated by Django 6.0 on 2025-12-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Cook', 'Cook'), ('Helper', 'Helper')], default='Helper', max_length=50, verbose_name='Role'),
        ),
    ]
