# Generated by Django 6.0 on 2025-12-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_alter_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Kirana', 'Kirana/Grocery'), ('Gas', 'Gas Cylinder/Fuel'), ('Vegetables', 'Vegetables (Sabzi)'), ('Milk', 'Milk/Dairy'), ('Auto', 'Auto Rickshaw/Transport'), ('Wood', 'Wood/Fuel'), ('Disposable', 'Disposable'), ('Coka and Namkeen, Biscuit', 'Coka and Namkeen, Biscuit'), ('Other', 'Other Expenses')], max_length=150, verbose_name='Category'),
        ),
    ]
