# Generated by Django 6.0 on 2025-12-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active Employee'),
        ),
        migrations.AddField(
            model_name='staff',
            name='leaving_date',
            field=models.DateField(blank=True, null=True, verbose_name='Leaving Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_mode',
            field=models.CharField(choices=[('Pending', '🔴 Pending / Due'), ('Cash', '🟢 Paid - Cash'), ('Online', '🔵 Paid - Online')], default='Online', max_length=20, verbose_name='Payment Status'),
        ),
    ]
